$env:POSTGRES_USER = "assetflow"
$env:POSTGRES_PASSWORD = "assetflow_secret"
$env:POSTGRES_DB = "assetflow"
$env:POSTGRES_HOST = "localhost"
$env:POSTGRES_PORT = "5432"
$env:JWT_SECRET_KEY = "dev_secret_key_change_in_production_abcdef1234567890"
$env:JWT_ALGORITHM = "HS256"
$env:ACCESS_TOKEN_EXPIRE_MINUTES = "30"
$env:REFRESH_TOKEN_EXPIRE_DAYS = "7"
$env:PASSWORD_RESET_TOKEN_EXPIRE_MINUTES = "15"
$env:ALLOWED_ORIGINS = "http://localhost:5173,http://localhost:3000"
$env:APP_ENV = "development"
$env:APP_NAME = "AssetFlow"
$env:FRONTEND_URL = "http://localhost:5173"
$env:MAIL_USERNAME = ""
$env:MAIL_PASSWORD = ""
$env:MAIL_FROM = "noreply@assetflow.com"
$env:MAIL_PORT = "587"
$env:MAIL_SERVER = "smtp.gmail.com"
$env:MAIL_STARTTLS = "True"
$env:MAIL_SSL_TLS = "False"
$env:SUPER_ADMIN_EMAIL = "superadmin@assetflow.com"
$env:SUPER_ADMIN_PASSWORD = "SuperAdmin@123!"
$env:SUPER_ADMIN_FULL_NAME = "Super Administrator"

C:\Python313\python.exe -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
